// Bilingual display names and patterns from the bundled Registry and its legacy labels.
// Published Registry text stays immutable; these names are only used in the authoring interface.
export const LANGUAGE_TARGET_RULE_LABELS: ReadonlyArray<{
  id: string; chinese: string; english: string; pattern?: string;
}> = [
  {"id":"GR-A1-001","chinese":"说明身份或类别","english":"State identity or category","pattern":"A 是 B"},
  {"id":"GR-A1-002","chinese":"说明姓名","english":"State a given name","pattern":"A 叫 X"},
  {"id":"GR-A1-003","chinese":"说明姓氏","english":"State a surname","pattern":"A 姓 X"},
  {"id":"GR-A1-004","chinese":"表达拥有或关系","english":"Express possession or a relationship","pattern":"A 有 B"},
  {"id":"GR-A1-005","chinese":"否定拥有或存在","english":"Negate possession or existence","pattern":"A 没有 B"},
  {"id":"GR-A1-006","chinese":"说明某处有人或物","english":"State that a person or object is at a location","pattern":"地点 + 有 + 人／物"},
  {"id":"GR-A1-007","chinese":"说明所在地点","english":"State a location","pattern":"A 在 B"},
  {"id":"GR-A1-008","chinese":"说明基本方位","english":"State a basic spatial relationship","pattern":"A 在 B 里／上／下／前面／后面／左边／右边／旁边"},
  {"id":"GR-A1-009","chinese":"表达基本动作","english":"Express a basic action","pattern":"主语 + 动词 + 宾语"},
  {"id":"GR-A1-010","chinese":"表达时间地点动作顺序","english":"Order time, subject, location, and action","pattern":"时间 + 主语 + 地点 + 动作"},
  {"id":"GR-A1-011","chinese":"描述基本性质或状态","english":"Describe a basic quality or state","pattern":"主语 + 很 + 形容词；主语 + 形容词"},
  {"id":"GR-A1-012","chinese":"表达明显程度或变化","english":"Express an obvious degree or change","pattern":"太 + 形容词 + 了"},
  {"id":"GR-A1-013","chinese":"表达轻微程度","english":"Express a slight degree","pattern":"有点儿 + 形容词／状态"},
  {"id":"GR-A1-014","chinese":"表达所属或简单修饰","english":"Express possession or simple modification","pattern":"A 的 B"},
  {"id":"GR-A1-015","chinese":"表示人物复数","english":"Mark a plural group of people","pattern":"人称代词／人物名词 + 们"},
  {"id":"GR-A1-016","chinese":"表达基本数量","english":"Express a basic quantity","pattern":"数词 + 量词 + 名词"},
  {"id":"GR-A1-017","chinese":"询问基本数量","english":"Ask about a basic quantity","pattern":"几／多少 + 量词 + 名词"},
  {"id":"GR-A1-018","chinese":"表达简单序数","english":"Express a simple ordinal","pattern":"第 + 数词 + 量词／名词"},
  {"id":"GR-A1-019","chinese":"提出一般疑问","english":"Ask a yes-no question","pattern":"陈述句 + 吗？"},
  {"id":"GR-A1-020","chinese":"提出正反疑问","english":"Ask an affirmative-negative question","pattern":"动词／形容词 + 不 + 动词／形容词"},
  {"id":"GR-A1-021","chinese":"确认身份或存在","english":"Confirm identity or existence","pattern":"是不是；有没有"},
  {"id":"GR-A1-022","chinese":"确认能力或许可","english":"Confirm ability or permission","pattern":"能不能；可不可以"},
  {"id":"GR-A1-023","chinese":"询问人物或事物","english":"Ask about a person or thing","pattern":"谁；什么"},
  {"id":"GR-A1-024","chinese":"询问选择","english":"Ask about a choice","pattern":"哪 + 量词／名词"},
  {"id":"GR-A1-025","chinese":"询问地点","english":"Ask about a location","pattern":"哪里／哪儿"},
  {"id":"GR-A1-026","chinese":"询问日期时间价格","english":"Ask about a date, time, or price","pattern":"几；多少；几点；几号"},
  {"id":"GR-A1-027","chinese":"询问方法或情况","english":"Ask about a method or condition","pattern":"怎么 + 动词；怎么样"},
  {"id":"GR-A1-028","chinese":"简单追问","english":"Ask a simple follow-up question","pattern":"名词／代词 + 呢？"},
  {"id":"GR-A1-029","chinese":"否定习惯、意愿或一般事实","english":"Negate a habit, intention, or general fact","pattern":"不 + 动词／形容词"},
  {"id":"GR-A1-030","chinese":"否定已发生或表示没有","english":"Negate a completed action or express absence","pattern":"没（有）+ 动词／名词"},
  {"id":"GR-A1-031","chinese":"表达简单禁止或劝阻","english":"Express a simple prohibition or warning","pattern":"不要／别 + 动词"},
  {"id":"GR-A1-032","chinese":"表达意愿、需要或计划","english":"Express an intention, need, or plan","pattern":"想／要／需要 + 名词／动词短语"},
  {"id":"GR-A1-033","chinese":"表达能力或许可","english":"Express ability or permission","pattern":"会／能／可以 + 动词"},
  {"id":"GR-A1-034","chinese":"表达当前动作","english":"Express a current action","pattern":"在／正在 + 动词"},
  {"id":"GR-A1-035","chinese":"表达简单完成","english":"Express simple completion","pattern":"动词 + 了 + 宾语"},
  {"id":"GR-A1-036","chinese":"表达新情况或状态变化","english":"Express a new situation or change of state","pattern":"句末了"},
  {"id":"GR-A1-037","chinese":"连接名词性成分","english":"Coordinate nominal elements","pattern":"A 和／跟 B"},
  {"id":"GR-A1-038","chinese":"表达相同或补充情况","english":"Express a parallel or additional fact","pattern":"也 + 谓语"},
  {"id":"GR-A1-039","chinese":"表达全体或共同情况","english":"Express a shared situation involving all members","pattern":"都 + 谓语"},
  {"id":"GR-A1-040","chinese":"表达继续、另外或仍然","english":"Express continuation, addition, or persistence","pattern":"还 + 谓语／名词"},
  {"id":"GR-A1-041","chinese":"表达再次动作","english":"Express a repeated or later action","pattern":"再 + 动词"},
  {"id":"GR-A1-042","chinese":"表达共同参与","english":"Express joint participation","pattern":"一起 + 动词"},
  {"id":"GR-A1-043","chinese":"礼貌提出请求","english":"Make a polite request","pattern":"请 + 动词／短语"},
  {"id":"GR-A1-044","chinese":"请求许可或确认可行性","english":"Request permission or confirm feasibility","pattern":"可以 + 动词 + 吗？"},
  {"id":"GR-A1-045","chinese":"弱化简单请求","english":"Soften a simple request","pattern":"动词 + 一下"},
  {"id":"GR-A1-046","chinese":"提出简单建议或确认","english":"Make a simple suggestion or confirmation","pattern":"短句 + 吧"},
  {"id":"GR-A1-047","chinese":"给出物品或服务","english":"Give an item or provide a service","pattern":"给 + 人 + 物"},
  {"id":"GR-A1-048","chinese":"转告信息","english":"Relay information","pattern":"告诉 + 人 + 信息"},
  {"id":"GR-A1-049","chinese":"表达移动到地点","english":"Express movement to a location","pattern":"去／来 + 地点"},
  {"id":"GR-A1-050","chinese":"表达交通方式和目的地","english":"Express a mode of transport and destination","pattern":"坐 + 交通工具 + 去 + 地点"},
  {"id":"GR-A1-051","chinese":"表达起止范围","english":"Express a range from a starting point to an endpoint","pattern":"从 + 时间／地点 + 到 + 时间／地点"},
  {"id":"GR-A1-052","chinese":"表达上下交通工具","english":"Express boarding or alighting from transport","pattern":"在 + 地点 + 上车／下车"},
  {"id":"GR-A1-053","chinese":"给出一步式方向","english":"Give a one-step direction","pattern":"一直走；左转；右转；往 + 地点 + 走"},
  {"id":"GR-A1-054","chinese":"表达具体日期","english":"Express a specific date","pattern":"年／月／日／号；星期 + 数字"},
  {"id":"GR-A1-055","chinese":"表达钟点","english":"Express a clock time","pattern":"上午／下午／晚上 + 数字 + 点／分／半"},
  {"id":"GR-A1-056","chinese":"表达相对日期","english":"Express a relative date","pattern":"今天／明天／昨天 + 谓语"},
  {"id":"GR-A1-057","chinese":"表达选择确认","english":"Confirm a choice between alternatives","pattern":"A 还是 B？"},
  {"id":"GR-A1-058","chinese":"表达限制","english":"Express a limitation","pattern":"只 + 动词／数量"},
  {"id":"GR-A1-059","chinese":"表达简单先后","english":"Express a simple sequence","pattern":"先 + 动词，再 + 动词"},
  {"id":"GR-A1-060","chinese":"表示接近或距离","english":"Express proximity or distance","pattern":"A 离 B 近／远"},
  {"id":"PRAG-GREET","chinese":"问候","english":"Greeting"},
  {"id":"PRAG-FAREWELL","chinese":"告别","english":"Farewell"},
  {"id":"PRAG-THANK","chinese":"感谢","english":"Thanking"},
  {"id":"PRAG-RESPOND-THANK","chinese":"回应感谢","english":"Responding to thanks"},
  {"id":"PRAG-APOLOGISE","chinese":"道歉","english":"Apologising"},
  {"id":"PRAG-RESPOND-APOLOGY","chinese":"回应道歉","english":"Responding to an apology"},
  {"id":"PRAG-POLITE-OPEN","chinese":"礼貌开始提问","english":"Opening a question politely"},
  {"id":"PRAG-REQUEST","chinese":"提出简单请求","english":"Making a simple request"},
  {"id":"PRAG-ASK-HELP","chinese":"请求帮助","english":"Asking for help"},
  {"id":"PRAG-CONFIRM","chinese":"确认信息","english":"Confirming information"},
  {"id":"PRAG-REQUEST-REPEAT","chinese":"请求重复","english":"Asking for repetition"},
  {"id":"PRAG-REQUEST-SLOWER","chinese":"请求放慢","english":"Asking someone to slow down"},
  {"id":"PRAG-NONUNDERSTANDING","chinese":"表示没听懂","english":"Signalling non-understanding"},
  {"id":"PRAG-ACCEPT-INVITATION","chinese":"接受邀请","english":"Accepting an invitation"},
  {"id":"PRAG-DECLINE-INVITATION","chinese":"拒绝邀请","english":"Declining an invitation"},
  {"id":"PRAG-ASK-RELATED-QUESTION","chinese":"提出相关问题","english":"Asking a related question"},
  {"id":"PRAG-ORDER","chinese":"点餐或购买","english":"Ordering or buying"},
  {"id":"PRAG-RELAY","chinese":"面向指定对象转告","english":"Relaying information to a specified recipient"},
];
