// Display glosses follow the registered A1 senses, without changing pinned content labels.
export const LEXICAL_GLOSSES: Record<string, string> = {
  "你好": "Hello",
  "您好": "Hello (polite)",
  "早上好": "Good morning",
  "晚上好": "Good evening",
  "再见": "Goodbye",
  "谢谢": "Thank you",
  "不客气": "You're welcome",
  "对不起": "Sorry",
  "没关系": "That's all right",
  "没事": "No problem; don't worry",
  "请": "Please",
  "请问": "Excuse me, may I ask",
  "喂": "Hello (on the phone)",
  "好": "Good; OK",
  "不好": "Not good; unsuitable",
  "可以": "May; can; be allowed to",
  "不可以": "Must not; not allowed",
  "不要": "Do not; do not want",
  "好吗": "OK?; is that all right?",
  "可以吗": "May I?; is that possible?",
  "怎么样": "How is it?; how about it?",
  "请再说一次": "Please say that again",
  "请说慢一点": "Please speak a little more slowly",
  "我没听懂": "I didn't understand what I heard",
  "请帮我": "Please help me",
  "可以帮我吗": "Could you help me?",
  "欢迎": "Welcome",
  "我": "I; me",
  "我们": "We; us",
  "你": "You (singular)",
  "你们": "You (plural)",
  "您": "You (polite singular)",
  "他": "He; him",
  "她": "She; her",
  "它": "It",
  "他们": "They; them (male or mixed group)",
  "她们": "They; them (female group)",
  "大家": "Everyone",
  "自己": "Oneself",
  "人": "Person; people",
  "谁": "Who",
  "什么": "What",
  "哪": "Which",
  "哪个": "Which one",
  "哪些": "Which ones",
  "哪里": "Where",
  "这": "This",
  "那": "That",
  "这个": "This one",
  "那个": "That one",
  "这些": "These",
  "那些": "Those",
  "这里": "Here",
  "那里": "There",
  "名字": "Name",
  "姓名": "Full name",
  "姓": "Surname; be surnamed",
  "叫": "Be called; be named",
  "国籍": "Nationality",
  "国家": "Country",
  "来自": "Come from",
  "住": "Live; reside",
  "城市": "City",
  "年龄": "Age",
  "岁": "Years old",
  "生日": "Birthday",
  "电话": "Telephone; phone call",
  "手机": "Mobile phone",
  "电话号码": "Telephone number",
  "号码": "Number; identification number",
  "工作": "Work; job",
  "学习": "Study; learn",
  "学生": "Student",
  "老师": "Teacher",
  "同学": "Classmate",
  "同事": "Colleague",
  "朋友": "Friend",
  "家": "Home; family",
  "家人": "Family member",
  "爸爸": "Dad; father",
  "妈妈": "Mom; mother",
  "哥哥": "Older brother",
  "姐姐": "Older sister",
  "弟弟": "Younger brother",
  "妹妹": "Younger sister",
  "儿子": "Son",
  "女儿": "Daughter",
  "孩子": "Child",
  "先生": "Mr.; sir",
  "女士": "Ms.; madam",
  "男": "Male",
  "女": "Female",
  "大学": "University",
  "大学生": "University student",
  "学校": "School",
  "公司": "Company",
  "职业": "Occupation",
  "出生日期": "Date of birth",
  "爱": "Love",
  "喜欢": "Like",
  "想": "Want to; intend to; think",
  "要": "Want; need; be going to",
  "需要": "Need",
  "会": "Can (learned ability); will",
  "能": "Can; be able to",
  "知道": "Know (a fact)",
  "懂": "Understand",
  "认识": "Know (a person); recognize",
  "觉得": "Feel; think",
  "看": "Look; watch; read",
  "看见": "See",
  "听": "Listen",
  "听见": "Hear",
  "说": "Say; speak",
  "说话": "Speak; talk",
  "读": "Read; read aloud",
  "读书": "Read books; study",
  "写": "Write; type",
  "学": "Learn; study",
  "问": "Ask",
  "回答": "Answer",
  "给": "Give; to; for",
  "告诉": "Tell",
  "帮": "Help",
  "帮忙": "Help; lend a hand",
  "找": "Look for",
  "来": "Come",
  "去": "Go",
  "到": "Arrive; reach",
  "回": "Return",
  "走": "Walk; leave",
  "坐": "Sit; take (transport)",
  "开": "Open; drive",
  "关": "Close; turn off",
  "做": "Do; make",
  "做饭": "Cook",
  "吃": "Eat",
  "喝": "Drink",
  "买": "Buy",
  "卖": "Sell",
  "穿": "Wear; put on",
  "睡觉": "Sleep",
  "起床": "Get up",
  "休息": "Rest",
  "上班": "Go to work; be at work",
  "下班": "Finish work",
  "上课": "Attend class; start class",
  "下课": "Finish class",
  "参加": "Take part in; attend",
  "见面": "Meet",
  "开始": "Start; begin",
  "结束": "End; finish",
  "打电话": "Make a phone call",
  "开车": "Drive a car",
  "看病": "See a doctor",
  "生病": "Be ill; fall ill",
  "不": "Not; no",
  "是": "Be; am; is; are",
  "有": "Have; there is; there are",
  "没有": "Do not have; there is no",
  "怎么": "How",
  "大": "Big; large",
  "小": "Small; little",
  "多": "Many; much",
  "少": "Few; little (quantity)",
  "新": "New",
  "贵": "Expensive",
  "便宜": "Cheap; inexpensive",
  "漂亮": "Beautiful; pretty",
  "好看": "Good-looking; attractive",
  "好吃": "Delicious; tasty",
  "高兴": "Happy; pleased",
  "忙": "Busy",
  "冷": "Cold",
  "热": "Hot",
  "早": "Early",
  "晚": "Late",
  "快": "Fast; soon",
  "慢": "Slow",
  "近": "Near",
  "远": "Far",
  "对": "Correct; right",
  "错": "Wrong; incorrect",
  "真": "Really; truly",
  "非常": "Very; extremely",
  "很": "Very",
  "太": "Too; so (degree)",
  "颜色": "Color",
  "大小": "Size",
  "红色": "Red",
  "白色": "White",
  "黑色": "Black",
  "蓝色": "Blue",
  "绿色": "Green",
  "舒服": "Comfortable; well",
  "不舒服": "Unwell; uncomfortable",
  "有时间": "Have time; be available",
  "没时间": "Have no time; be unavailable",
  "零": "Zero",
  "一": "One",
  "二": "Two (counting)",
  "两": "Two (before a measure word)",
  "三": "Three",
  "四": "Four",
  "五": "Five",
  "六": "Six",
  "七": "Seven",
  "八": "Eight",
  "九": "Nine",
  "十": "Ten",
  "百": "Hundred",
  "千": "Thousand",
  "半": "Half",
  "几": "How many; a few",
  "多少": "How many; how much",
  "个": "General measure word",
  "本": "Measure word for books",
  "杯": "Cup; cupful (measure word)",
  "件": "Measure word for clothing or items",
  "口": "Measure word for family members",
  "块": "Yuan (colloquial); piece; chunk",
  "元": "Yuan (currency unit)",
  "位": "Polite measure word for people",
  "张": "Measure word for flat objects",
  "份": "Portion; copy (measure word)",
  "年": "Year",
  "月": "Month",
  "日": "Day (written dates)",
  "号": "Day of the month; number",
  "星期": "Week; day of the week",
  "星期日": "Sunday",
  "今天": "Today",
  "明天": "Tomorrow",
  "昨天": "Yesterday",
  "今年": "This year",
  "明年": "Next year",
  "去年": "Last year",
  "现在": "Now",
  "时间": "Time",
  "时候": "Time; moment",
  "日期": "Date",
  "早上": "Early morning",
  "上午": "Morning (before noon)",
  "中午": "Noon; midday",
  "下午": "Afternoon",
  "晚上": "Evening; night",
  "点": "O'clock; time of day",
  "分": "Minute (clock time)",
  "分钟": "Minute (duration)",
  "小时": "Hour",
  "几点": "What time",
  "什么时候": "When",
  "一共": "Altogether; in total",
  "天": "Day",
  "地方": "Place; area",
  "地点": "Location; venue",
  "房间": "Room",
  "教室": "Classroom",
  "电影院": "Cinema; movie theater",
  "商店": "Shop; store",
  "超市": "Supermarket",
  "餐厅": "Restaurant; dining room",
  "酒店": "Hotel",
  "书店": "Bookstore",
  "图书馆": "Library",
  "车站": "Station; stop",
  "机场": "Airport",
  "医院": "Hospital",
  "洗手间": "Restroom; toilet",
  "门": "Door; gate",
  "门口": "Doorway; entrance",
  "楼": "Building; floor",
  "楼层": "Floor; level",
  "路": "Road; route",
  "路口": "Intersection; crossroads",
  "附近": "Nearby; vicinity",
  "上": "Up; above; on",
  "下": "Down; below; under",
  "里": "Inside",
  "外": "Outside",
  "前面": "In front",
  "后面": "Behind; at the back",
  "左边": "Left side",
  "右边": "Right side",
  "旁边": "Beside; next to",
  "入口": "Entrance",
  "出口": "Exit",
  "开门": "Open the door; open for business",
  "关门": "Close the door; close for business",
  "营业时间": "Opening hours",
  "禁止": "Prohibited; forbidden",
  "往": "Toward",
  "一直走": "Go straight ahead",
  "左转": "Turn left",
  "右转": "Turn right",
  "地图": "Map",
  "开放": "Open; accessible",
  "关闭": "Close; shut down",
  "怎么走": "How do I get there?",
  "东西": "Thing; object",
  "书": "Book",
  "电脑": "Computer",
  "电视": "Television; TV",
  "电影": "Movie; film",
  "衣服": "Clothes",
  "杯子": "Cup; glass",
  "椅子": "Chair",
  "桌子": "Table; desk",
  "票": "Ticket",
  "车票": "Travel ticket",
  "菜单": "Menu",
  "卡": "Card",
  "钱": "Money",
  "水": "Water",
  "茶": "Tea",
  "牛奶": "Milk",
  "饮料": "Drink; beverage",
  "饭": "Meal; cooked rice",
  "米饭": "Cooked rice",
  "面包": "Bread",
  "菜": "Dish; vegetable",
  "水果": "Fruit",
  "苹果": "Apple",
  "鸡蛋": "Egg",
  "食物": "Food",
  "早饭": "Breakfast",
  "午饭": "Lunch",
  "晚饭": "Dinner; evening meal",
  "一杯": "One cup; one glass",
  "一份": "One portion; one copy",
  "多少钱": "How much does it cost?",
  "一共多少钱": "How much is it altogether?",
  "结账": "Pay the bill; check out",
  "付款": "Pay; make a payment",
  "车": "Vehicle; car",
  "公交车": "Bus",
  "出租车": "Taxi",
  "地铁": "Subway; metro",
  "火车": "Train",
  "飞机": "Airplane",
  "火车站": "Train station",
  "线路": "Route; transit line",
  "上车": "Get on; board",
  "下车": "Get off; alight",
  "哪一路车": "Which bus route",
  "入住": "Check in (at a hotel)",
  "房间号": "Room number",
  "退房": "Check out (of a hotel)",
  "几点退房": "What time is checkout?",
  "病": "Illness; be ill",
  "身体": "Body; physical health",
  "头": "Head",
  "头疼": "Have a headache",
  "疼": "Hurt; be painful",
  "药": "Medicine",
  "帮助": "Help; assistance",
  "我头疼": "I have a headache",
  "我不舒服": "I feel unwell",
  "我需要医生": "I need a doctor",
  "医生": "Doctor",
  "课": "Class; lesson",
  "课程": "Course",
  "活动": "Activity; event",
  "报名": "Sign up; register",
  "会议": "Meeting",
  "排班": "Work schedule; schedule shifts",
  "消息": "Message; information",
  "短信": "Text message; SMS",
  "邮件": "Email",
  "回复": "Reply",
  "收到": "Receive",
  "问题": "Question; problem",
  "汉语": "Chinese language",
  "中文": "Chinese language; written Chinese",
  "汉字": "Chinese character",
  "字": "Character (writing)",
  "预约": "Book; make an appointment",
  "邀请": "Invite; invitation",
  "有空": "Be free; have time",
  "没空": "Be busy; have no time",
  "课表": "Class timetable",
  "天气": "Weather",
  "雨": "Rain",
  "下雨": "Rain; be raining",
  "雪": "Snow",
  "白天": "Daytime",
  "一下": "Briefly; a little (softens a request)",
  "一些": "Some; a few",
  "一点儿": "A little; a bit",
  "也": "Also; too",
  "了": "Completion or change-of-state particle",
  "们": "Plural suffix for people",
  "再": "Again; then",
  "只": "Only",
  "吗": "Yes-no question particle",
  "吧": "Suggestion or confirmation particle",
  "呢": "Follow-up question or current-state particle",
  "和": "And",
  "在": "At; in; action in progress",
  "有些": "Some",
  "有点儿": "A little; somewhat",
  "正在": "Be in the process of; action in progress",
  "的": "Possessive or noun-modifying particle",
  "第": "Ordinal-number prefix",
  "还": "Still; also; in addition",
  "都": "All; both",
  "从": "From",
  "跟": "With; and",
  "每天": "Every day",
  "星期几": "What day of the week",
  "几号": "What date (day of the month)",
  "几点开始": "What time does it start?",
  "下雪": "Snow; be snowing",
};

// Some registered characters occur only inside words; gloss their meaning in that scope.
export const CHARACTER_GLOSSES: Record<string, string> = {
  ...Object.fromEntries(Object.entries(LEXICAL_GLOSSES).filter(([form]) => [...form].length === 1)),
  "口": "Opening; family-member measure word",
  "点": "Point; location; a little; o'clock",
  "会": "Can; will; meeting (in 会议)",
  "见": "See; meet",
  "谢": "Thank (in 谢谢)",
  "客": "Guest; polite (in 不客气)",
  "气": "Air; manner (in 天气, 不客气)",
  "起": "Rise; start",
  "没": "Not; have not",
  "系": "Connection (in 没关系)",
  "事": "Matter; affair",
  "可": "May; can (in 可以)",
  "以": "Part of 可以 (may; can)",
  "怎": "How (in 怎么)",
  "么": "Question-word element (in 什么, 怎么)",
  "样": "Way; manner (in 怎么样)",
  "次": "Time; occurrence",
  "欢": "Joy; pleased (in 欢迎, 喜欢)",
  "迎": "Welcome; greet",
  "自": "Self; from (in 自己, 来自)",
  "己": "Self (in 自己)",
  "什": "What (in 什么)",
  "些": "Some; plural quantity",
  "名": "Name",
  "国": "Country",
  "籍": "Membership; nationality (in 国籍)",
  "城": "City",
  "市": "City; market",
  "龄": "Age (in 年龄)",
  "生": "Birth; student (in 生日, 学生)",
  "电": "Electricity; electronic",
  "话": "Speech; words",
  "手": "Hand",
  "机": "Machine; device",
  "码": "Code; number",
  "工": "Work",
  "作": "Do; work",
  "习": "Learn; practice (in 学习)",
  "老": "Respectful prefix (in 老师)",
  "师": "Teacher",
  "同": "Same; fellow",
  "朋": "Friend (in 朋友)",
  "友": "Friend",
  "爸": "Dad; father",
  "妈": "Mom; mother",
  "哥": "Older brother",
  "姐": "Older sister",
  "弟": "Younger brother",
  "妹": "Younger sister",
  "儿": "Child; noun or quantity suffix",
  "子": "Child; noun suffix",
  "孩": "Child (in 孩子)",
  "先": "First; title element (in 先生)",
  "士": "Person; title element (in 女士)",
  "校": "School",
  "公": "Public; company element (in 公司)",
  "司": "Company element (in 公司)",
  "职": "Job; occupation",
  "业": "Occupation; business",
  "出": "Go out; exit",
  "期": "Period; date",
  "喜": "Like; joy",
  "需": "Need",
  "知": "Know",
  "道": "Know (in 知道)",
  "认": "Recognize",
  "识": "Know; recognize",
  "觉": "Feel; sleep (in 觉得, 睡觉)",
  "得": "Feel (in 觉得)",
  "答": "Answer",
  "告": "Tell",
  "诉": "Tell (in 告诉)",
  "睡": "Sleep",
  "床": "Bed",
  "休": "Rest",
  "息": "Rest; information (in 休息, 消息)",
  "班": "Work shift; class",
  "参": "Participate (in 参加)",
  "加": "Join; add",
  "面": "Face; side; flour (in 面包)",
  "始": "Begin",
  "结": "Finish; settle (in 结束, 结账)",
  "束": "End (in 结束)",
  "打": "Make (a phone call)",
  "便": "Cheap (in 便宜)",
  "宜": "Inexpensive (in 便宜)",
  "漂": "Pretty (in 漂亮)",
  "亮": "Bright; pretty (in 漂亮)",
  "高": "High; happy (in 高兴)",
  "兴": "Happy; pleased (in 高兴)",
  "非": "Very (in 非常)",
  "常": "Very (in 非常)",
  "颜": "Color (in 颜色)",
  "色": "Color",
  "红": "Red",
  "白": "White; daytime (in 白天)",
  "黑": "Black",
  "蓝": "Blue",
  "绿": "Green",
  "舒": "Comfortable (in 舒服)",
  "服": "Clothes; comfortable (in 衣服, 舒服)",
  "时": "Time; hour",
  "间": "Room; interval",
  "星": "Week element (in 星期)",
  "今": "This; current (in 今天, 今年)",
  "明": "Next (in 明天, 明年)",
  "昨": "Previous day (in 昨天)",
  "现": "Present; current",
  "候": "Time; moment (in 时候)",
  "午": "Noon",
  "中": "Middle; Chinese (in 中文)",
  "钟": "Clock; minute element (in 分钟)",
  "共": "Together; total",
  "地": "Place; ground",
  "方": "Place; direction",
  "房": "Room; house",
  "教": "Teach; teaching",
  "室": "Room",
  "影": "Film; image",
  "院": "Institution; facility",
  "商": "Commerce; shop element",
  "店": "Shop; establishment",
  "超": "Super- (in 超市)",
  "餐": "Meal; dining",
  "厅": "Hall; room",
  "酒": "Hotel element (in 酒店)",
  "图": "Picture; map; book element (in 图书馆)",
  "馆": "Public building; facility",
  "站": "Station; stop",
  "场": "Place; venue",
  "医": "Medical; doctor",
  "洗": "Wash",
  "层": "Floor; level",
  "附": "Near (in 附近)",
  "前": "Front; before",
  "后": "Back; behind",
  "左": "Left",
  "边": "Side",
  "右": "Right (direction)",
  "旁": "Beside",
  "入": "Enter",
  "营": "Operate; business (in 营业时间)",
  "禁": "Prohibit",
  "止": "Stop",
  "直": "Straight",
  "转": "Turn",
  "放": "Open (in 开放)",
  "闭": "Close; shut",
  "东": "Thing element (in 东西)",
  "西": "Thing element (in 东西)",
  "脑": "Brain; computer element (in 电脑)",
  "视": "See; television element (in 电视)",
  "衣": "Clothing",
  "椅": "Chair",
  "桌": "Table; desk",
  "单": "List (in 菜单)",
  "牛": "Cow (in 牛奶)",
  "奶": "Milk",
  "饮": "Drink",
  "料": "Material; beverage element (in 饮料)",
  "米": "Rice",
  "包": "Bread element (in 面包)",
  "果": "Fruit",
  "苹": "Apple (in 苹果)",
  "鸡": "Chicken; hen (in 鸡蛋)",
  "蛋": "Egg",
  "食": "Food; eat",
  "物": "Thing; object",
  "账": "Bill; account",
  "付": "Pay",
  "款": "Money; payment",
  "交": "Transport element (in 公交车)",
  "租": "Rent; hire",
  "铁": "Iron; railway element (in 地铁)",
  "火": "Train element (in 火车)",
  "飞": "Fly",
  "线": "Line; route",
  "退": "Leave; check out (in 退房)",
  "身": "Body",
  "体": "Body; physical",
  "助": "Help; assist",
  "程": "Course element (in 课程)",
  "活": "Activity element (in 活动)",
  "动": "Move; activity",
  "报": "Register (in 报名)",
  "议": "Discuss; meeting element (in 会议)",
  "排": "Arrange; schedule",
  "消": "Message element (in 消息)",
  "短": "Short",
  "信": "Letter; message",
  "邮": "Mail",
  "复": "Reply (in 回复)",
  "收": "Receive",
  "题": "Question; problem",
  "汉": "Chinese (language or writing)",
  "语": "Language",
  "文": "Writing; written language",
  "预": "In advance",
  "约": "Arrange; appointment",
  "邀": "Invite",
  "空": "Free; available",
  "表": "Table; schedule",
  "正": "Right now (in 正在)",
  "每": "Every; each",
};
